# EP (Endpoint) controllers for UBCC basic framework

Import('*')

import os

if env['CONF']['PROTOCOL'] != 'CHI':
    Return()

repo_root = os.path.abspath(os.path.join(Dir('#').abspath, '..'))
zmq_include = os.path.join(repo_root, 'thirdparty/zeromq/include')
zmq_lib = os.path.join(repo_root, 'thirdparty/zeromq/lib')

env.Append(CPPPATH=[repo_root, zmq_include])
env.Append(LIBPATH=[zmq_lib])
env.Append(LIBS=['zmq'])
env.Append(LINKFLAGS=['-pthread', f'-Wl,-rpath,{zmq_lib}'])

SimObject('EPController.py', sim_objects=['EPController'])
SimObject('EPRNFController.py', sim_objects=['EPRNFController'])
SimObject('EPSNFController.py', sim_objects=['EPSNFController'])
SimObject('EPBackend.py', sim_objects=['EPBackend'])
SimObject('MetaRNFController.py', sim_objects=['MetaRNFController'])
SimObject('UBIOModule.py', sim_objects=['UBIOModule'])
SimObject('UBAdapter.py', sim_objects=['UBAdapter'])

Source('NodeAddressMap.cc')
Source('EPRNFController.cc')
Source('EPSNFController.cc')
Source('EPBackend.cc')
Source('MetaRNFController.cc')
Source('UBCCController.cc')
Source('ResidentDir.cc')
Source('UBIOModule.cc')
Source('UBAdapter.cc')
Source('BackstoreSchemaA.cc')
Source('BackstoreSchemaC.cc')
Source('M4SelfTest.cc')
Source('M5SelfTest.cc')
Source('M6SelfTest.cc')
Source('M7SelfTest.cc')
Source('M8SelfTest.cc')
Source(File(os.path.join(repo_root, 'framework/Port.cc')))

DebugFlag('RubyEP')
DebugFlag('RubyEPVerbose')
DebugFlag('UBLatency')
DebugFlag('UBInvariant')
