# EP (Endpoint) controllers for UBCC basic framework

Import('*')

if env['CONF']['PROTOCOL'] != 'CHI':
    Return()

SimObject('EPController.py', sim_objects=['EPController'])
SimObject('EPRNFController.py', sim_objects=['EPRNFController'])
SimObject('EPSNFController.py', sim_objects=['EPSNFController'])
SimObject('EPBackend.py', sim_objects=['EPBackend'])
SimObject('MetaRNFController.py', sim_objects=['MetaRNFController'])
SimObject('UBIOModule.py', sim_objects=['UBIOModule'])
SimObject('UBAdapter.py', sim_objects=['UBAdapter'])

Source('NodeAddressMap.cc')
Source('EPRNFController.cc')
Source('EPSNFController.cc')
Source('EPBackend.cc')
Source('MetaRNFController.cc')
Source('UBCCController.cc')
Source('ResidentDir.cc')
Source('UBIOModule.cc')
Source('UBAdapter.cc')
Source('BackstoreSchemaA.cc')
Source('BackstoreSchemaC.cc')
Source('M4SelfTest.cc')
Source('M5SelfTest.cc')
Source('M6SelfTest.cc')
Source('M7SelfTest.cc')
Source('M8SelfTest.cc')

DebugFlag('RubyEP')
DebugFlag('RubyEPVerbose')
DebugFlag('UBLatency')
DebugFlag('UBInvariant')
